/**
 * Design Token Generator using D3
 * Generates color ramps and design tokens for the restaurant management system
 * Inspired by Petpooja's clean, modern aesthetic
 */

import * as d3 from 'd3-color';
import * as d3Scale from 'd3-scale';
import * as d3Interpolate from 'd3-interpolate';
import * as fs from 'fs';
import * as path from 'path';

// Base colors inspired by Petpooja's palette
const BRAND_BASE = '#0F172A'; // Deep navy (slate-900)
const ACCENT_BASE = '#F97316'; // Warm orange
const SUCCESS_BASE = '#10B981'; // Emerald green
const WARNING_BASE = '#F59E0B'; // Amber
const DANGER_BASE = '#EF4444'; // Red
const INFO_BASE = '#3B82F6'; // Blue

/**
 * Generate a color ramp using D3 interpolation
 * Returns 11 colors (0-10) that map to Tailwind's 50-950 scale
 */
function generateColorRamp(
  startColor: string,
  endColor: string,
  steps: number = 11
): string[] {
  const interpolator = d3Interpolate.interpolateRgb(startColor, endColor);
  const colors: string[] = [];
  
  for (let i = 0; i < steps; i++) {
    const t = i / (steps - 1);
    const color = interpolator(t);
    colors.push(color);
  }
  
  return colors;
}

/**
 * Generate a neutral ramp (light to dark)
 */
function generateNeutralRamp(baseColor: string, steps: number = 11): string[] {
  // Create a light version (almost white) and dark version
  const lightColor = '#FFFFFF';
  const darkColor = baseColor;
  
  // Generate ramp from light to dark
  const interpolator = d3Interpolate.interpolateRgb(lightColor, darkColor);
  const colors: string[] = [];
  
  for (let i = 0; i < steps; i++) {
    const t = i / (steps - 1);
    const color = interpolator(t);
    colors.push(color);
  }
  
  return colors;
}

/**
 * Generate an accent ramp (light to dark through the base color)
 */
function generateAccentRamp(baseColor: string, steps: number = 11): string[] {
  const lightColor = d3.rgb(baseColor).brighter(2.5).toString();
  const darkColor = d3.rgb(baseColor).darker(2.5).toString();
  
  const interpolator = d3Interpolate.interpolateRgb(lightColor, darkColor);
  const colors: string[] = [];
  
  // Ensure the base color is at the middle
  for (let i = 0; i < steps; i++) {
    const t = i / (steps - 1);
    let color = interpolator(t);
    
    // Adjust to ensure base color is at step 5 (500 equivalent)
    if (i === 5) {
      color = baseColor;
    }
    
    colors.push(color);
  }
  
  return colors;
}

/**
 * Calculate if a color is light or dark (for text contrast)
 */
function getContrastColor(bgColor: string): string {
  const rgb = d3.rgb(bgColor);
  const luminance = (0.299 * rgb.r + 0.587 * rgb.g + 0.114 * rgb.b) / 255;
  return luminance > 0.5 ? '#000000' : '#FFFFFF';
}

/**
 * Generate CSS variables
 */
function generateCSSVariables(): string {
  const brandRamp = generateNeutralRamp(BRAND_BASE);
  const accentRamp = generateAccentRamp(ACCENT_BASE);
  const successRamp = generateAccentRamp(SUCCESS_BASE);
  const warningRamp = generateAccentRamp(WARNING_BASE);
  const dangerRamp = generateAccentRamp(DANGER_BASE);
  const infoRamp = generateAccentRamp(INFO_BASE);
  
  // Map to Tailwind scale: 0->50, 1->100, ..., 10->950
  const tailwindMap = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
  
  let css = `/**
 * Design Tokens - Auto-generated by generate-design-tokens.ts
 * Do not edit manually. Run: npm run design:tokens
 */

:root {
  /* Brand Colors (Neutral) */
`;
  
  brandRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    const contrast = getContrastColor(color);
    css += `  --brand-${shade}: ${color};\n`;
    css += `  --on-brand-${shade}: ${contrast};\n`;
  });
  
  css += `\n  /* Accent Colors */\n`;
  accentRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    const contrast = getContrastColor(color);
    css += `  --accent-${shade}: ${color};\n`;
    css += `  --on-accent-${shade}: ${contrast};\n`;
  });
  
  css += `\n  /* Status Colors - Success */\n`;
  successRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    const contrast = getContrastColor(color);
    css += `  --status-success-${shade}: ${color};\n`;
    css += `  --on-status-success-${shade}: ${contrast};\n`;
  });
  
  css += `\n  /* Status Colors - Warning */\n`;
  warningRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    const contrast = getContrastColor(color);
    css += `  --status-warning-${shade}: ${color};\n`;
    css += `  --on-status-warning-${shade}: ${contrast};\n`;
  });
  
  css += `\n  /* Status Colors - Danger */\n`;
  dangerRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    const contrast = getContrastColor(color);
    css += `  --status-danger-${shade}: ${color};\n`;
    css += `  --on-status-danger-${shade}: ${contrast};\n`;
  });
  
  css += `\n  /* Status Colors - Info */\n`;
  infoRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    const contrast = getContrastColor(color);
    css += `  --status-info-${shade}: ${color};\n`;
    css += `  --on-status-info-${shade}: ${contrast};\n`;
  });
  
  css += `}\n`;
  
  return css;
}

/**
 * Generate Tailwind config extension
 */
function generateTailwindConfig(): string {
  const brandRamp = generateNeutralRamp(BRAND_BASE);
  const accentRamp = generateAccentRamp(ACCENT_BASE);
  const successRamp = generateAccentRamp(SUCCESS_BASE);
  const warningRamp = generateAccentRamp(WARNING_BASE);
  const dangerRamp = generateAccentRamp(DANGER_BASE);
  const infoRamp = generateAccentRamp(INFO_BASE);
  
  const tailwindMap = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
  
  let config = `/**
 * Tailwind Design Tokens - Auto-generated by generate-design-tokens.ts
 * Do not edit manually. Run: npm run design:tokens
 */

module.exports = {
  brand: {
`;
  
  brandRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    config += `    ${shade}: 'var(--brand-${shade})',\n`;
  });
  
  config += `  },\n  accent: {\n`;
  accentRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    config += `    ${shade}: 'var(--accent-${shade})',\n`;
  });
  
  config += `  },\n  status: {\n    success: {\n`;
  successRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    config += `      ${shade}: 'var(--status-success-${shade})',\n`;
  });
  
  config += `    },\n    warning: {\n`;
  warningRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    config += `      ${shade}: 'var(--status-warning-${shade})',\n`;
  });
  
  config += `    },\n    danger: {\n`;
  dangerRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    config += `      ${shade}: 'var(--status-danger-${shade})',\n`;
  });
  
  config += `    },\n    info: {\n`;
  infoRamp.forEach((color, i) => {
    const shade = tailwindMap[i];
    config += `      ${shade}: 'var(--status-info-${shade})',\n`;
  });
  
  config += `    },\n  },\n};\n`;
  
  return config;
}

/**
 * Main function
 */
function main() {
  console.log('🎨 Generating design tokens...\n');
  
  const rootDir = path.resolve(__dirname, '..');
  const cssDir = path.join(rootDir, 'packages', 'ui', 'src', 'styles');
  const configDir = path.join(rootDir, 'packages', 'ui', 'src');
  
  // Ensure directories exist
  if (!fs.existsSync(cssDir)) {
    fs.mkdirSync(cssDir, { recursive: true });
  }
  
  // Generate CSS variables
  const css = generateCSSVariables();
  const cssPath = path.join(cssDir, 'brand.css');
  fs.writeFileSync(cssPath, css);
  console.log(`✅ Generated: ${cssPath}`);
  
  // Generate Tailwind config
  const tailwindConfig = generateTailwindConfig();
  const configPath = path.join(configDir, 'tailwind.brand.js');
  fs.writeFileSync(configPath, tailwindConfig);
  console.log(`✅ Generated: ${configPath}`);
  
  console.log('\n✨ Design tokens generated successfully!');
  console.log('\nNext steps:');
  console.log('1. Import brand.css in your app globals.css');
  console.log('2. Extend tailwind.config.js with tailwind.brand.js');
  console.log('3. Use classes like: bg-brand-900, text-accent-500, bg-status-success-600');
}

main();

